import { describe, it, expect } from "vitest";
import { computeModifiedFiles, buildCommitMessage } from "../../stages/execute-commit.js";
import type { Story } from "../../types/execution-plan.js";
import type { VerifyResult } from "../../stages/execute-verify.js";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const testStory: Story = {
  id: "US-01",
  title: "Types and scaffold",
  specSections: ["1.1"],
  dependencies: [],
  sourceFiles: ["src/types/index.ts", "src/utils/file-io.ts"],
  complexity: "low",
  rolesUsed: ["analyst"],
  stepFile: "plans/steps/US-01.md",
  status: "passed",
  attempts: 1,
  maxAttempts: 3,
  committed: false,
  commitHash: null,
};

describe("execute-commit", () => {
  it("computeModifiedFiles deduplicates and sorts", () => {
    const implReport = `# Implementation Report
## FILES CREATED
| File | Lines | Exports |
|------|:-----:|---------|
| src/types/index.ts | 50 | Story |
| src/new-file.ts | 30 | newFn |
`;
    const fixReport = `# Fix Report
## FIXES APPLIED
| # | File | Description |
|---|------|-------------|
| 1 | src/utils/file-io.ts | Fixed import |
| 2 | src/another.ts | Added missing export |
`;
    const files = computeModifiedFiles(testStory, implReport, [fixReport]);
    expect(files).toContain("src/types/index.ts");
    expect(files).toContain("src/utils/file-io.ts");
    expect(files).toContain("src/new-file.ts");
    expect(files).toContain("src/another.ts");
    // Sorted
    expect(files).toEqual([...files].sort());
    // No duplicates
    expect(new Set(files).size).toBe(files.length);
  });

  it("buildCommitMessage includes story ID", () => {
    const testDir = join(process.cwd(), ".test-commit-msg");
    mkdirSync(join(testDir, "reports", "US-01"), { recursive: true });
    writeFileSync(join(testDir, "reports", "US-01", "test-report.md"), "## STATUS: PASS\n| AC-0 | lint | cmd | ok | PASS |");
    writeFileSync(join(testDir, "reports", "US-01", "eval-report.md"), "## VERDICT: PASS\n| EC-1 | desc | ref | cmd | ok | PASS |");

    const verifyResult: VerifyResult = {
      passed: true,
      attempts: 1,
      testReportPath: join(testDir, "reports", "US-01", "test-report.md"),
      evalReportPath: join(testDir, "reports", "US-01", "eval-report.md"),
      parserConfidence: "matched",
    };

    const message = buildCommitMessage(testStory, verifyResult);
    expect(message).toContain("feat(US-01)");
    expect(message).toContain("Types and scaffold");
    expect(message).toContain("Generated by Hive Mind v3");
    expect(message).not.toContain("--no-verify");

    rmSync(testDir, { recursive: true, force: true });
  });

  it("--no-verify never used in source", async () => {
    const { readFileSync } = await import("node:fs");
    const { resolve, dirname } = await import("node:path");
    const { fileURLToPath } = await import("node:url");
    const thisDir = dirname(fileURLToPath(import.meta.url));
    const content = readFileSync(
      resolve(thisDir, "../../stages/execute-commit.ts"),
      "utf-8",
    );
    expect(content).not.toContain("--no-verify");
  });
});
