import type { Story } from "../types/execution-plan.js";
import { getSourceFilePaths } from "../types/execution-plan.js";
import type { VerifyResult } from "./execute-verify.js";
import { runShell } from "../utils/shell.js";
import { readFileSafe } from "../utils/file-io.js";
import { parseImplReport, parseFixReport } from "../reports/parser.js";
import { getReportPath } from "../reports/templates.js";
import type { HiveMindConfig } from "../config/schema.js";
import { join } from "node:path";

export interface CommitResult {
  committed: boolean;
  commitHash: string | null;
  error?: string;
}

export function computeModifiedFiles(
  story: Story,
  implReportContent: string,
  fixReportContents: string[],
): string[] {
  const files = new Set<string>(getSourceFilePaths(story.sourceFiles));

  // Add files from impl-report
  const implResult = parseImplReport(implReportContent);
  for (const f of implResult.filesCreated) {
    files.add(f);
  }

  // Add files from fix-reports
  for (const fixContent of fixReportContents) {
    const fixResult = parseFixReport(fixContent);
    for (const fix of fixResult.fixesApplied) {
      files.add(fix.file);
    }
  }

  return [...files].sort();
}

export function buildCommitMessage(story: Story, verifyResult: VerifyResult): string {
  const testContent = readFileSafe(verifyResult.testReportPath) ?? "";
  const evalContent = readFileSafe(verifyResult.evalReportPath) ?? "";

  const acLines = testContent.match(/\|\s*AC-/g) ?? [];
  const ecLines = evalContent.match(/\|\s*EC-/g) ?? [];
  const acTotal = acLines.length;
  const ecTotal = ecLines.length;

  return `feat(${story.id}): ${story.title}

ACs: ${acTotal}/${acTotal} passed | ECs: ${ecTotal}/${ecTotal} passed
Attempts: ${verifyResult.attempts} of ${story.maxAttempts}
Lint: PASS

Generated by Hive Mind v3`;
}

export async function runCommit(
  story: Story,
  hiveMindDir: string,
  verifyResult: VerifyResult,
  _config: HiveMindConfig,
  moduleCwd?: string,
): Promise<CommitResult> {
  // Collect modified files
  const implReportPath = join(hiveMindDir, getReportPath(story.id, "impl-report.md"));
  const implContent = readFileSafe(implReportPath) ?? "";

  const fixContents: string[] = [];
  for (let i = 1; i <= story.maxAttempts; i++) {
    const fixPath = join(hiveMindDir, getReportPath(story.id, `fix-report-${i}.md`));
    const content = readFileSafe(fixPath);
    if (content) fixContents.push(content);
  }

  const modifiedFiles = computeModifiedFiles(story, implContent, fixContents)
    .filter(f => f.includes("/") || f.includes("."));
  if (modifiedFiles.length === 0) {
    return { committed: false, commitHash: null, error: "No modified files to commit" };
  }

  const fileList = modifiedFiles.map(f => `"${f}"`).join(" ");
  const commitMessage = buildCommitMessage(story, verifyResult);

  // Attempt 1: git add + commit (hooks always run)
  const shellOpts = moduleCwd ? { cwd: moduleCwd } : undefined;
  const addResult = await runShell(`git add ${fileList}`, shellOpts);
  if (addResult.exitCode !== 0) {
    return { committed: false, commitHash: null, error: `git add failed: ${addResult.stderr}` };
  }

  let commitResult = await runShell(`git commit -m "${commitMessage.replace(/"/g, '\\"')}"`, shellOpts);

  if (commitResult.exitCode !== 0) {
    // Pre-commit hook may have modified files — re-stage and retry once
    console.log("Pre-commit hook may have modified files. Re-staging and retrying...");
    await runShell(`git add ${fileList}`, shellOpts);
    commitResult = await runShell(`git commit -m "${commitMessage.replace(/"/g, '\\"')}"`, shellOpts);

    if (commitResult.exitCode !== 0) {
      return {
        committed: false,
        commitHash: null,
        error: `Commit failed after retry: ${commitResult.stderr}`,
      };
    }
  }

  // Extract commit hash
  const hashMatch = commitResult.stdout.match(/\[[\w-]+\s+([a-f0-9]+)\]/);
  const commitHash = hashMatch?.[1] ?? null;

  return { committed: true, commitHash };
}
